version: "3"

services:
  postgres:
    container_name: tsundoku
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWARD
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
